# Generated by Django 3.1.6 on 2021-02-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.IntegerField(max_length=5)),
                ('operatingAirline', models.CharField(max_length=10)),
                ('departureCity', models.CharField(max_length=10)),
                ('arrivalCity', models.CharField(max_length=10)),
                ('dateDeparture', models.DateField()),
                ('timeDeparture', models.TimeField()),
            ],
        ),
    ]
