# Generated by Django 3.1.6 on 2021-02-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0004_auto_20210212_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flightNumber',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='passport',
        ),
    ]
