# Generated by Django 3.1.6 on 2021-02-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0005_auto_20210212_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flightNumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
