# Generated by Django 3.1.6 on 2021-02-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0007_auto_20210213_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flightNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='firstName',
            field=models.CharField(max_length=10),
        ),
    ]
